[project]
name = "al-pipe"
version = "0.1.0"
description = "Active learning pipeline aimed at reducing the need for intensive biological data generation"
readme = "README.md"
authors = [
    { name = "Zelun Li", email = "lizelun@westlake.edu.cn" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.11.3",
]

[tool.ruff]
# Set the maximum line length to 79.
line-length = 79

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
extend-select = [
    "E501", # max line-length
    "D", # pydocstyle
    "UP", #pyupgrade
]

[tool.ruff.lint.pydocstyle]
convention = "google"
