# @package _global_

defaults:
  - _self_ # setting composition order
  - datasets: random_promo_pTpA
  - model: one_hot
  - evaluator: default
  - first_batch: random
  - active_learning: default
  - query: random
  - logger: wandb
  - paths: default
  - hydra: default
  - trainer: default
  - regression: MLP


task_name: "test_run"
device: "cpu"
seed: 42
al_iterations: 5