data_path : "random_promo/" # no need for the first forward slash
data_name : "sub_sample_pTpA_All.csv" 
batch_size: 32 # Needs to be divisible by the number of devices (e.g., if in a distributed setup)
train_val_test_pool_split:
  train: 0.2
  val: 0.1
  test: 0.1
  pool: 0.6
num_workers: 1
pin_memory: False
shuffle: True
MAX_LENGTH: 150